<?php

namespace Kunstmaan\AdminListBundle\Tests\AdminList\FilterType\ORM;

use Kunstmaan\AdminListBundle\AdminList\FilterType\ORM\EnumerationFilterType;
use Symfony\Component\HttpFoundation\Request;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-26 at 15:06:50.
 *
 * @coversNothing
 */
class EnumerationFilterTypeTest extends ORMFilterTypeTestCase
{
    /**
     * @var EnumerationFilterType
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new EnumerationFilterType('enumeration', 'b');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers \Kunstmaan\AdminListBundle\AdminList\FilterType\ORM\EnumerationFilterType::bindRequest
     */
    public function testBindRequest()
    {
        $request = new Request(['filter_comparator_enumeration' => 'in', 'filter_value_enumeration' => [1, 2]]);

        $data = [];
        $uniqueId = 'enumeration';
        $this->object->bindRequest($request, $data, $uniqueId);

        $this->assertSame(['comparator' => 'in', 'value' => [1, 2]], $data);
    }

    /**
     * @param string $comparator  The comparator
     * @param string $whereClause The where clause
     * @param mixed  $value       The value
     * @param mixed  $testValue   The test value
     *
     * @covers \Kunstmaan\AdminListBundle\AdminList\FilterType\ORM\EnumerationFilterType::apply
     * @dataProvider applyDataProvider
     */
    public function testApply($comparator, $whereClause, $value, $testValue)
    {
        $qb = $this->getQueryBuilder();
        $qb->select('b')
          ->from('Entity', 'b');
        $this->object->setQueryBuilder($qb);
        $this->object->apply(['comparator' => $comparator, 'value' => $value], 'enumeration');

        $this->assertSame("SELECT b FROM Entity b WHERE b.enumeration $whereClause", $qb->getDQL());
        if ($testValue) {
            $this->assertSame($value, $qb->getParameter('var_enumeration')->getValue());
        }
    }

    /**
     * @return array
     */
    public static function applyDataProvider()
    {
        return [
          ['in', 'IN(:var_enumeration)', [1, 2], true],
          ['notin', 'NOT IN(:var_enumeration)', [1, 2], true],
        ];
    }

    /**
     * @covers \Kunstmaan\AdminListBundle\AdminList\FilterType\ORM\EnumerationFilterType::getTemplate
     */
    public function testGetTemplate()
    {
        $this->assertSame('KunstmaanAdminListBundle:FilterType:enumerationFilter.html.twig', $this->object->getTemplate());
    }
}
