<?php

namespace Kunstmaan\AdminListBundle\Tests\AdminList\FilterType\ORM;

use Kunstmaan\AdminListBundle\AdminList\FilterType\ORM\StringFilterType;
use Symfony\Component\HttpFoundation\Request;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-26 at 13:21:34.
 *
 * @coversNothing
 */
class StringFilterTypeTest extends ORMFilterTypeTestCase
{
    /**
     * @var StringFilterType
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new StringFilterType('string', 'b');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers \Kunstmaan\AdminListBundle\AdminList\FilterType\ORM\StringFilterType::bindRequest
     */
    public function testBindRequest()
    {
        $request = new Request(['filter_comparator_string' => 'equals', 'filter_value_string' => 'TheStringValue']);

        $data = [];
        $uniqueId = 'string';
        $this->object->bindRequest($request, $data, $uniqueId);

        $this->assertSame(['comparator' => 'equals', 'value' => 'TheStringValue'], $data);
    }

    /**
     * @param string $comparator  The comparator
     * @param string $whereClause The where clause
     * @param mixed  $value       The value
     * @param mixed  $testValue   The test value
     *
     * @covers \Kunstmaan\AdminListBundle\AdminList\FilterType\ORM\StringFilterType::apply
     * @dataProvider applyDataProvider
     */
    public function testApply($comparator, $whereClause, $value, $testValue)
    {
        $qb = $this->getQueryBuilder();
        $qb->select('b')
            ->from('Entity', 'b');
        $this->object->setQueryBuilder($qb);
        $this->object->apply(['comparator' => $comparator, 'value' => $value], 'string');

        $this->assertSame("SELECT b FROM Entity b WHERE b.string $whereClause", $qb->getDQL());
        $this->assertSame($testValue, $qb->getParameter('var_string')->getValue());
    }

    /**
     * @return array
     */
    public static function applyDataProvider()
    {
        return [
            ['equals', '= :var_string', 'AStringValue1', 'AStringValue1'],
            ['notequals', '<> :var_string', 'AStringValue2', 'AStringValue2'],
            ['contains', 'LIKE :var_string', 'AStringValue3', '%AStringValue3%'],
            ['doesnotcontain', 'NOT LIKE :var_string', 'AStringValue4', '%AStringValue4%'],
            ['startswith', 'LIKE :var_string', 'AStringValue5', 'AStringValue5%'],
            ['endswith', 'LIKE :var_string', 'AStringValue6', '%AStringValue6'],
        ];
    }

    /**
     * @covers \Kunstmaan\AdminListBundle\AdminList\FilterType\ORM\StringFilterType::getTemplate
     */
    public function testGetTemplate()
    {
        $this->assertSame('KunstmaanAdminListBundle:FilterType:stringFilter.html.twig', $this->object->getTemplate());
    }
}
