<?php

namespace Kunstmaan\AdminListBundle\Tests\AdminList\FilterType\DBAL;

use Kunstmaan\AdminListBundle\AdminList\FilterType\DBAL\DateFilterType;
use Symfony\Component\HttpFoundation\Request;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-26 at 13:21:33.
 *
 * @coversNothing
 */
class DateFilterTypeTest extends DBALFilterTypeTestCase
{
    /**
     * @var DateFilterType
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new DateFilterType('date', 'e');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers \Kunstmaan\AdminListBundle\AdminList\FilterType\DBAL\DateFilterType::bindRequest
     */
    public function testBindRequest()
    {
        $request = new Request(['filter_comparator_date' => 'before', 'filter_value_date' => '01/01/2012']);

        $data = [];
        $uniqueId = 'date';
        $this->object->bindRequest($request, $data, $uniqueId);

        $this->assertSame(['comparator' => 'before', 'value' => '01/01/2012'], $data);
    }

    /**
     * @param string $comparator  The comparator
     * @param string $whereClause The where clause
     * @param mixed  $value       The value
     * @param mixed  $testValue   The test value
     *
     * @covers \Kunstmaan\AdminListBundle\AdminList\FilterType\DBAL\DateFilterType::apply
     * @dataProvider applyDataProvider
     */
    public function testApply($comparator, $whereClause, $value, $testValue)
    {
        $qb = $this->getQueryBuilder();
        $qb->select('*')
            ->from('entity', 'e');
        $this->object->setQueryBuilder($qb);
        $this->object->apply(['comparator' => $comparator, 'value' => $value], 'date');

        $this->assertSame("SELECT * FROM entity e WHERE e.date $whereClause", $qb->getSQL());
        $this->assertSame($testValue, $qb->getParameter('var_date'));
    }

    /**
     * @return array
     */
    public static function applyDataProvider()
    {
        return [
            ['before', '<= :var_date', '20/12/2012', '2012-12-20'],
            ['after', '> :var_date', '21/12/2012', '2012-12-21'],
        ];
    }

    /**
     * @covers \Kunstmaan\AdminListBundle\AdminList\FilterType\DBAL\DateFilterType::getTemplate
     */
    public function testGetTemplate()
    {
        $this->assertSame('KunstmaanAdminListBundle:FilterType:dateFilter.html.twig', $this->object->getTemplate());
    }
}
